AgentOps Implementation
joaomdmoura/crewAI pull request #411
Opened 2024-04-02 22:19 UTC by bboynton97

Integrates AgentOps.

Adds support for tracking LLM calls, Agents, and Tool usage.
Extends documentation to include AgentOps implementation guide and examples

2024-04-04 01:20 UTC, bboynton97 commented
Don't merge this as is. We need to handle the case where agentops isn't installed more gracefully. Working on this now.

2024-04-04 21:51 UTC, bboynton97 commented on src/crewai/crew.py
> +        if agentops:
@joaomdmoura: this addition means that if the developer is using agentops, we will set the parent key. This way, Crew will have access to some run data in this case.

we can also change the conditional to `if agentops and self.share_crew` if you'd rather

2024-04-11 07:42 UTC, ajaywingify commented
@joaomdmoura possible to merge this branch soon? We really need AgentOps to monitor the performance of a support bot we're building using Crew.

2024-04-20 01:56 UTC, joaomdmoura requested changes

2024-04-20 01:56 UTC, joaomdmoura commented on pyproject.toml
> +agentops = "^0.1.1"
Let's make it optional, same way we do to crewai-tools, so we don't add the extra dependency for everyone, feel unnecessary if people are not using agent ops

2024-04-20 01:56 UTC, joaomdmoura commented on pyproject.toml
> +agentops = { version = "^0.1.1", optional = true }
Updating it to be an option dependency, so we might need to add some fallback when importing the agent ops

2024-04-20 15:20 UTC, joaomdmoura commented
temporarily merging this for the weekend

2024-04-20 15:20 UTC, merged